Implemented face detection filter
ugnelis/ros-cameras-controller pull request #20
Opened 2018-10-16 02:23 UTC by rummanwaqar

Closes #14 
Hacktoberfest :+1:

2018-10-16 06:22 UTC, ugnelis requested changes
Overall, nice job, but, please, fix code style.

2018-10-16 06:22 UTC, ugnelis commented on image_processing_filters/include/image_processing_filters/FaceDetectionFilterNodelet.h
> +    std::string face_cascade_string_;
Please use camel case.

2018-10-16 06:22 UTC, ugnelis commented on image_processing_filters/include/image_processing_filters/FaceDetectionFilterNodelet.h
> +    cv::CascadeClassifier face_cascade_;
Please use camel case.

2018-10-16 06:22 UTC, ugnelis commented on image_processing_filters/src/FaceDetectionFilterNodelet.cpp
> +          face_cascade_string_(){
I missing space after `()`

2018-10-16 06:22 UTC, ugnelis commented on image_processing_filters/src/FaceDetectionFilterNodelet.cpp
> +  FaceDetectionFilterNodelet::FaceDetectionFilterNodelet()
Please keep consistency: Either after namespace use spaces before every functions or don't use any.

2018-10-16 06:22 UTC, ugnelis commented on image_processing_filters/src/FaceDetectionFilterNodelet.cpp
> +void FaceDetectionFilterNodelet::onInit() {
Please keep consistency: Either after namespace use spaces before every functions or don't use any.

2018-10-16 06:22 UTC, ugnelis commented on image_processing_filters/src/FaceDetectionFilterNodelet.cpp
> +    if( !face_cascade_.load( face_cascade_string_ ) ) {
Please, don't use old school spacing. It should be: `if (!face_cascade_.load(face_cascade_string_)) {`.

2018-10-16 06:22 UTC, ugnelis commented on image_processing_filters/src/FaceDetectionFilterNodelet.cpp
> +    face_cascade_.detectMultiScale( greyImage, faces, 1.1, 2, 0|CV_HAAR_SCALE_IMAGE, cv::Size(30, 30) );
Old school spacing :(

2018-10-16 06:22 UTC, ugnelis commented on image_processing_filters/src/FaceDetectionFilterNodelet.cpp
> +    for( size_t i = 0; i < faces.size(); i++ )
Bad spacing.

2018-10-16 06:22 UTC, ugnelis commented on image_processing_filters/src/FaceDetectionFilterNodelet.cpp
> +      cv::Point center( faces[i].x + faces[i].width*0.5, faces[i].y + faces[i].height*0.5 );
It should be `cv::Point center(faces[i].x + faces[i].width * 0.5, faces[i].y + faces[i].height * 0.5);`

2018-10-16 06:22 UTC, ugnelis commented on image_processing_filters/src/FaceDetectionFilterNodelet.cpp
> +      cv::ellipse( receivedImage, center,
Spacing.

2018-10-16 06:22 UTC, ugnelis commented on image_processing_filters/src/FaceDetectionFilterNodelet.cpp
> +                   cv::Size( faces[i].width*0.5, faces[i].height*0.5),
Spacing.

2018-10-16 06:22 UTC, ugnelis commented on image_processing_filters/src/FaceDetectionFilterNodelet.cpp
> +                   0, 0, 360, cv::Scalar( 255, 0, 255 ), 4, 8, 0 );
Spacing.

2018-10-16 06:22 UTC, ugnelis commented on image_processing_filters/src/FaceDetectionFilterNodelet.cpp
> +#include <pluginlib/class_list_macros.h>
This include should be first because it is not local include.

2018-10-16 06:58 UTC, rummanwaqar commented
@ugnelis formatting is fixed.

2018-10-16 07:09 UTC, ugnelis requested changes
Some fixes should be made.

2018-10-16 07:09 UTC, ugnelis commented on image_processing_filters/src/FaceDetectionFilterNodelet.cpp
>      for( size_t i = 0; i < faces.size(); i++ )
Should be `for (size_t i = 0; i < faces.size(); i++) {`

2018-10-16 07:09 UTC, ugnelis commented on image_processing_filters/src/FaceDetectionFilterNodelet.cpp
> +    if(!faceCascade_.load(faceCascadeString_)) {
It should be `if<space>(`.

2018-10-17 05:04 UTC, ugnelis approved these changes
Good job :)

2018-10-17 05:04 UTC, merged